/* Generated By:JavaCC: Do not edit this line. ChannelDefParserConstants.java */
package form.channel;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ChannelDefParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int ENUM = 8;
  /** RegularExpression Id. */
  int STRING_T = 9;
  /** RegularExpression Id. */
  int NUMBER_T = 10;
  /** RegularExpression Id. */
  int BOOLEAN = 11;
  /** RegularExpression Id. */
  int LPAREN = 12;
  /** RegularExpression Id. */
  int RPAREN = 13;
  /** RegularExpression Id. */
  int LBRACE = 14;
  /** RegularExpression Id. */
  int RBRACE = 15;
  /** RegularExpression Id. */
  int LBRACKET = 16;
  /** RegularExpression Id. */
  int RBRACKET = 17;
  /** RegularExpression Id. */
  int SEMICOLON = 18;
  /** RegularExpression Id. */
  int COLON = 19;
  /** RegularExpression Id. */
  int COMMA = 20;
  /** RegularExpression Id. */
  int SHARP = 21;
  /** RegularExpression Id. */
  int DOLLAR = 22;
  /** RegularExpression Id. */
  int AT = 23;
  /** RegularExpression Id. */
  int IDENT = 24;
  /** RegularExpression Id. */
  int NUMBER = 25;
  /** RegularExpression Id. */
  int LETTER = 26;
  /** RegularExpression Id. */
  int DIGIT = 27;
  /** RegularExpression Id. */
  int STRING = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"enum\"",
    "\"string\"",
    "\"number\"",
    "\"boolean\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\"#\"",
    "\"$\"",
    "\"@\"",
    "<IDENT>",
    "<NUMBER>",
    "<LETTER>",
    "<DIGIT>",
    "<STRING>",
    "\"=\"",
  };

}
